default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 4 } %>
  url: <%= ENV.fetch('DATABASE_URL') %>

test:
  <<: *default

development:
  <<: *default

homolog:
  <<: *default

production:
  <<: *default
